@startuml

javafx.Application <|-- InventoryProgram
InventoryProgram <-- InventoryManagerController
InventoryManagerController <-- FileManager
FileManager <-- HTMLSave
FileManager <-- TSVSave

InventoryManagerController <-- InventoryItem
InventorySearch <-- InventoryItem
InventoryManagerController <-- InventorySearch

class InventoryProgram
{
    + Main()
    + Start()
}


class InventoryManagerController
{
    + SearchBar()
    + SaveClicked()
    + LoadClicked()
    + AddClicked()

    + validator()
}


class InventorySearch
{
    - ObservableList<InventoryItem>: TableList, ResultList

    + InventorySearch(ObservableList<InventoryItem>)
    + SearchList(String)
}


class InventoryItem
{
    - String: Name
    - String: SerialNumber
    - String: Value

    + InventoryItem(String, String, String)

    + getName()
    + setName(String)

    + getSerialNumber()
    + setSerialNumber(String)

    + getValue()
    + setValue(String)
}


class FileManager
{
    + String: filename

    + SaveFile(String)

    + LoadFile(String)

    - ExtensionType(String)
}

class HTMLSave
{

}

class TSVSave
{

}


@enduml