@startuml

javafx.Application <|-- InventoryProgram
InventoryProgram <-- InventoryManagerController
InventoryManagerController <-- FileManager
FileManager <-- HTMLSave
FileManager <-- TSVSave

InventoryManagerController <-- InventoryItem
InventoryList <-- InventoryItem

class InventoryProgram
{
    + Main()
    + Start()
}


class InventoryManagerController
{
    - validSerialNumber

    + SearchBar()
    + SaveClicked()
    + LoadClicked()
    + AddClicked()
}


class InventoryList
{
    + ObservableList<InventoryItem>

    + getList()
    + clearList()

    + addItem(Double, String, String)
    + editItemValue(Double)
    + editItemName(String)
    + editItemSerialNumber(String)
}


class InventoryItem
{
    - String: Name
    - String: SerialNumber
    - String: Value

    + InventoryItem(String, String, String)

    + getName()
    + setName(String)

    + getSerialNumber()
    + setSerialNumber(String)

    + getValue()
    + setValue(String)
}


class FileManager
{
    + String: filename

    + SaveFile(String)

    + LoadFile(String)

    - ExtensionType(String)
}

class HTMLSave
{

}

class TSVSave
{

}


@enduml